#!/usr/bin/env python3
"""
Build the quiz dataset from the Our World Atlas source.

Reads the atlas-source files that also feed Our-World-Atlas.pdf and emits
data/atlas.js — a plain script that assigns window.ATLAS. It is a .js file
rather than .json on purpose: fetch() is blocked under file://, so shipping
the data as a script keeps the app working when index.html is opened by
double-clicking it, with no server involved.

Usage:  python3 tools/build_quiz_data.py [--source ../atlas-source]
"""

import argparse
import glob
import json
import os
import sys

# Fields the quiz actually uses. Dropping the rest (lat/lon, ccn3, render
# hints) keeps the shipped payload to roughly a third of the source size.
KEEP = (
    "a3", "a2", "name", "official", "continent", "subregion", "capital",
    "population", "pop_year", "area", "landlocked", "languages",
    "currencies", "note",
)


def build(source_dir):
    data_path = os.path.join(source_dir, "data.json")
    if not os.path.isfile(data_path):
        sys.exit(f"error: {data_path} not found — pass --source with the atlas-source path")

    with open(data_path, encoding="utf-8") as fh:
        countries = json.load(fh)

    content = {}
    for path in sorted(glob.glob(os.path.join(source_dir, "content_*.json"))):
        with open(path, encoding="utf-8") as fh:
            content.update(json.load(fh))

    out = []
    for country in countries:
        record = {k: country.get(k) for k in KEEP}
        extra = content.get(country["a3"], {})
        # sig/fun/places carry the capital-city colour: the blurb, the fun
        # fact and three landmarks. Landmark questions depend on places.
        record["sig"] = extra.get("sig")
        record["fun"] = extra.get("fun")
        record["places"] = extra.get("places", [])
        out.append(record)

    return out


def report(rows):
    """Fail loudly on gaps — a silently thin dataset makes for a thin quiz."""
    problems = []
    for r in rows:
        if not r.get("capital"):
            problems.append(f"{r['name']}: no capital")
        if not r.get("sig"):
            problems.append(f"{r['name']}: no capital blurb")
        if len(r.get("places") or []) < 3:
            problems.append(f"{r['name']}: {len(r.get('places') or [])} landmarks (want 3)")

    continents = {}
    for r in rows:
        continents[r["continent"]] = continents.get(r["continent"], 0) + 1

    print(f"countries      : {len(rows)}")
    for name, count in sorted(continents.items(), key=lambda kv: -kv[1]):
        print(f"  {name:<15}: {count}")
    print(f"landmarks      : {sum(len(r['places']) for r in rows)}")
    print(f"fun facts      : {sum(1 for r in rows if r.get('fun'))}")
    print(f"currencies     : {len({c for r in rows for c in (r.get('currencies') or [])})} distinct")
    print(f"languages      : {len({l for r in rows for l in (r.get('languages') or [])})} distinct")

    if problems:
        print("\nGAPS:")
        for p in problems:
            print(f"  - {p}")
    return not problems


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default="../atlas-source",
                    help="directory holding data.json and content_*.json")
    ap.add_argument("--out", default="data/atlas.js")
    args = ap.parse_args()

    rows = build(args.source)
    clean = report(rows)

    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/build_quiz_data.py — do not edit by hand. */\n")
        fh.write(f"window.ATLAS = {payload};\n")

    size = os.path.getsize(args.out)
    print(f"\nwrote {args.out} ({size / 1024:.0f} KB)")
    sys.exit(0 if clean else 1)
